#!/bin/bash
# Author: Dhaval Koshti
# Date create: 01.07.2021
# Description: This script will show us the use of text in for loop
# Date modification: 01.07.2021

for i in eat run jump play
do
	echo "See Dhaval $i"
done
