#!/bin/bash
# Author: Dhaval Koshti
# Date create: 01.07.2021
# Description: This script will check, if variable values are being met
# Date modification: 01.07.2021

echo
echo "What is your name?"
echo
read name
echo "Hello $name"
echo
echo "do you like IT ?"
read like
echo

	if [ "$like" == y ]
	then
		echo "You are cool"
	elif [ "$like" == n ]
	then
		echo "You should try IT, Its a good carrier"
	else
		echo "Fuck off"
	fi
